
package View;
import base.ItensVendidosComprados;
import vendaitens.VendaItensRMI_Cliente;
/**
 * Panel responsável por mostrar os dados do comprador e o item que o comprador pretende comprar.
 * 
 * @author Ise
 */
public class notificarEvento extends javax.swing.JPanel {
    private VendaItensRMI_Cliente cli;
   
    public notificarEvento() {
        initComponents();
        
    }
    public void setCliente(VendaItensRMI_Cliente cli){
        this.cli = cli;
        preenche();
    }
    public void preenche() {
        ItensVendidosComprados item = cli.itemVenda;
        lblAno.setText(item.getAno());
        lblMes.setText(item.getMes());
        lblBandeira.setText(item.getBandeira());
        lblCartao.setText(item.getNumeroCartao());
        lblCogSeg.setText(item.getCodSeg());
        lblCod.setText(item.getCodItem()+"");
        lblNomeItem.setText(item.getNomeItem());
        lblTitular.setText(item.getTitular());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCod = new javax.swing.JLabel();
        lblNomeItem = new javax.swing.JLabel();
        lblBandeira = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTitular = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCartao = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblCogSeg = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblMes = new javax.swing.JLabel();
        lblAno = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Seu produto está disponível!");

        jLabel2.setText("Nome do item:");

        lblCod.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCod.setText("Código do item");

        lblNomeItem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNomeItem.setText("Nome do item");

        lblBandeira.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBandeira.setText("Bandeira");

        jLabel3.setText("Bandeira do cartão:");

        jLabel5.setText("Número do cartão:");

        lblTitular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTitular.setText("nome do titular");

        jLabel4.setText("Nome do titular:");

        lblCartao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCartao.setText("numero do cartao");

        jLabel1.setText("Código do item:");

        jLabel7.setText("Código segurança");

        lblCogSeg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCogSeg.setText("código");

        jLabel8.setText("Vencimento:");

        lblMes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMes.setText("mes");

        lblAno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAno.setText("ano");

        jLabel9.setText("Mês:");

        jLabel10.setText("Ano:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMes)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAno))
                            .addComponent(jLabel8)
                            .addComponent(lblTitular)
                            .addComponent(jLabel4)
                            .addComponent(lblBandeira)
                            .addComponent(jLabel3)
                            .addComponent(lblNomeItem)
                            .addComponent(lblCod)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCartao)
                                    .addComponent(jLabel5))
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCogSeg)
                                    .addComponent(jLabel7)))))
                    .addComponent(jLabel6))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCod)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeItem)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBandeira)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCartao))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCogSeg)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMes)
                    .addComponent(jLabel9)
                    .addComponent(lblAno)
                    .addComponent(jLabel10))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblBandeira;
    private javax.swing.JLabel lblCartao;
    private javax.swing.JLabel lblCod;
    private javax.swing.JLabel lblCogSeg;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblNomeItem;
    private javax.swing.JLabel lblTitular;
    // End of variables declaration//GEN-END:variables
}
